files:
  fuku-at-sea:
    - https://energy.gov/sites/prod/files/2013/10/f3/AMS%20C12%20Sea%20Data.kmz
  fuku-iodine:
    - https://energy.gov/sites/prod/files/2014/01/f6/Iodine%20Deposition%20from%20Early%20Aerial%20Surveys.kmz
    